### ISSUE TITLE
OverflowError: bad numeric conversion: positive overflow in dispatchEventQueue

### ISSUE THREAD

**Issue by khanalesb** [devcartel/api#33]
Try to request .SSEA

 File "/export/scratch/devel/FlaskRFA/src/service.py", line 15, in procResponse
    for u in p.dispatchEventQueue():
OverflowError: bad numeric conversion: positive overflow
127.0.0.1 - - [15/Sep/2017 10:33:13] "GET /?ric=.SSEA HTTP/1.1" 500 -

Everything else seems to work...
I'm using Flask, python 2.7.3 and
pyrfa        8.2.1

**Comment by wiwat-tharateeraparb** [comment]
It may be safer to dispatch updates just like [consumer.py](https://github.com/devcartel/pyrfa/blob/master/examples/consumer.py). Second, it is possible that you didn't dispatch events fast enough. If you can send pyrfa.log to support@devcartel.com, I will take a look.

**Comment by khanalesb** [comment]
Looks like I didn't explain myself well enough:
application works for everything except for this symbol:  .SSEA
Timeout in dispatch doesn't change a thing.
Overflow - it is one item request (snapshot) - not even subscription.

**Comment by khanalesb** [comment]
Log:
[MarketPriceHandler::processResponse] MarketPrice Refresh: .SSEA.hEDD
[2017-10-06 09:42:54,218] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/export/scratch/software/python/flaskrfa/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/export/scratch/software/python/flaskrfa/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/export/scratch/software/python/flaskrfa/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/export/scratch/software/python/flaskrfa/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/export/scratch/software/python/flaskrfa/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/export/scratch/software/python/flaskrfa/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "src/service.py", line 55, in home
    res = fullRequest(p, ric)
  File "src/service.py", line 26, in fullRequest
    result = procResponse(p)
  File "src/service.py", line 15, in procResponse
    for u in p.dispatchEventQueue():
OverflowError: bad numeric conversion: positive overflow

**Comment by wiwat-tharateeraparb** [comment]
Looks like it could be a data decoding issue for this `.SSEA` RIC. We don't have this symbol in our lab. Are you able to turn on `traceMsg` in `pyrfa.cfg`, e.g.:

```
\Connections\Connection_RSSL1\traceMsg = true
\Connections\Connection_RSSL1\traceMsgFileName = "./out.txt"
```

This will enable PyRFA to log incoming data into a file. Then we can investigate which data format that causes this issue.

**Comment by Chen-Yi-Cheng** [comment]
I have the same issue of this, the ric is "/600085.SS".
The platform is docker offical python 3.7.3 image and pyrfa 8.5.3.

But there is one strange thing. If the develop platform is windows. Everything is ok.
If the platform is linux.  It will throw overflow exception.

The others rics are OK, except the rics of china.

Thanks

**Comment by wiwat-tharateeraparb** [comment]
Hi, we believe it could be some decoding issue. Can you try simple consumer app just to get this RIC  and set `\pyrfa\debug = true` just to see when the exception occurs.

**Comment by Chen-Yi-Cheng** [comment]
[issue.txt](https://github.com/devcartel/pyrfa/files/3405216/issue.txt)

Please reference the log file
` updates = p.dispatchEventQueue(100)
OverflowError: bad numeric conversion: positive overflow`

Thanks

**Comment by Chen-Yi-Cheng** [comment]
Dear Wiwat:
Is there any plan of this issue?
What kind of information that i can collect?
Thank you.

**Comment by wiwat-tharateeraparb** [comment]
@Chen-Yi-Cheng is it possible for us to access your IDN_SELECTFEED so we can consume .SS symbols? If so, please contact our support@devcartel.com for access information.
